spring.profiles.active: dev

spring.http.encodingcharset: UTF-8
spring.http.encodingenabled: true
spring.http.encodingforce: true
spring.messages.encoding: UTF-8

logging:config: classpath:logback-spring.xml

spring.mvc.throw-exception-if-no-handler-found: true

# seesion配置
server.servlet.session.timeout: 120m

# 网站域名配置，最后没有反斜杆
web.host: "http://wx.xxxxxx.com"



